// footer.js

import { globalState } from "../../reactive/state";

export function createFooter(pageNumber, totalPages) {
    const footer = document.createElement('footer');
    footer.className = 'page-footer';

    const leftSection = document.createElement('div');
    leftSection.className = 'footer-left';
    const formattedDateTime = new Date().toLocaleString();
    leftSection.innerHTML = `
        <p>Report Generated: ${formattedDateTime}</p>
        <p>Page ${pageNumber} of ${totalPages}</p>
    `;

    const centerSection = document.createElement('div');
    centerSection.className = 'footer-center';
    centerSection.textContent = globalState.getState().reportTitle || 'Report Title';

    const rightSection = document.createElement('div');
    rightSection.className = 'footer-right';
    const userInfo = JSON.parse(localStorage.getItem('user')) || {};
    rightSection.innerHTML = `
        <p>Report Generated By: ${userInfo.fname || ''} ${userInfo.lname || ''}</p>
        <p>Created With: 911 Emerge-N-See Report Generator</p>
    `;

    footer.appendChild(leftSection);
    footer.appendChild(centerSection);
    footer.appendChild(rightSection);

    return footer;
}
