// pageBuilder.js
import { getPageDimensions } from '../formUtils/dpiUtils.js';
import { globalState } from '../../reactive/state.js';
import { measureFooterHeight } from '../formUtils/measurementUtils.js';

export function scaleComponent(element, scaleRatio) {
    element.style.transform = `scale(${scaleRatio})`;
    element.style.transformOrigin = 'top left';
}

function createFooter(pageIndex, totalPages) {
    const footer = document.createElement('footer');
    footer.className = 'page-footer';

    // Left Section: Date and Page Number
    const leftSection = document.createElement('div');
    leftSection.className = 'footer-left';
    const formattedDateTime = new Date().toLocaleString();
    leftSection.innerHTML = `
        <p>Report Generated: ${formattedDateTime}</p>
        <p>Page ${pageIndex + 1} of ${totalPages}</p>
    `;

    // Center Section: Report Title
    const centerSection = document.createElement('div');
    centerSection.className = 'footer-center';
    centerSection.textContent = globalState.getState().reportTitle || 'Report Title';

    // Right Section: User and Tool Information
    const rightSection = document.createElement('div');
    rightSection.className = 'footer-right';
    const userInfo = JSON.parse(localStorage.getItem('user')) || {};
    rightSection.innerHTML = `
        <p>Report Generated By: ${userInfo.fname || ''} ${userInfo.lname || ''}</p>
        <p>Created With: 911 Emerge-N-See Report Generator</p>
    `;

    footer.appendChild(leftSection);
    footer.appendChild(centerSection);
    footer.appendChild(rightSection);

    return footer;
}

export function renderPages(pages) {
    const contentBody = document.getElementById('contentBody');
    contentBody.innerHTML = ''; // Clear previous content

    requestAnimationFrame(() => {
        const containerWidth = 0.9 * contentBody.offsetWidth;
        const { width, height } = getPageDimensions(containerWidth);

        const footerHeight = measureFooterHeight();
        const scaleRatio = globalState.getState().scaleRatio;
        const availableHeight = height - footerHeight * scaleRatio;

        pages.forEach((page, pageIndex) => {
            const pageContainer = document.createElement('div');
            pageContainer.className = 'page';
            pageContainer.style.width = `${width}px`;
            pageContainer.style.height = `${height}px`;
            pageContainer.style.position = 'relative';

            let currentPageHeight = 0;

            page.forEach((contentItem) => {
                const contentHeight = contentItem.element.offsetHeight * scaleRatio;

                if (currentPageHeight + contentHeight <= availableHeight) {
                    pageContainer.appendChild(contentItem.element);
                    currentPageHeight += contentHeight;
                } else {
                    contentBody.appendChild(pageContainer);
                    const newPageContainer = document.createElement('div');
                    newPageContainer.className = 'page';
                    newPageContainer.style.width = `${width}px`;
                    newPageContainer.style.height = `${height}px`;
                    newPageContainer.style.position = 'relative';

                    newPageContainer.appendChild(contentItem.element);
                    currentPageHeight = contentHeight;
                    pageContainer = newPageContainer;
                }
            });

            const footer = createFooter(pageIndex, pages.length);
            pageContainer.appendChild(footer);

            contentBody.appendChild(pageContainer);
        });

        const tables = document.querySelectorAll("table.report-table");
        tables.forEach((table, index) => {
            scaleTableComponent(table, scaleRatio);
            console.log(`Scaled table ${index + 1} with scale ratio: ${scaleRatio}`);
        });

        console.log("Rendered pages with footer and adjusted content height.");
    });
}

export function scaleTableComponent(table, scaleRatio) {
    if (!table || !(table instanceof HTMLElement)) {
        console.error("Invalid or missing table component for scaling");
        return;
    }

    console.log("Scaling table component with scaleRatio:", scaleRatio);

    // Scale header font-size, top/bottom padding
    const headerCells = table.querySelectorAll("th");
    headerCells.forEach((headerCell, index) => {
        const computedStyles = getComputedStyle(headerCell);
        const baseFontSize = parseFloat(computedStyles.fontSize);
        const basePaddingTop = parseFloat(computedStyles.paddingTop);
        const basePaddingBottom = parseFloat(computedStyles.paddingBottom);

        if (baseFontSize) {
            headerCell.style.fontSize = `${parseFloat(baseFontSize * scaleRatio - (scaleRatio / 10)).toFixed(0)}px`;
        }
        if (basePaddingTop) {
            headerCell.style.paddingTop = `${parseFloat(basePaddingTop * scaleRatio - (scaleRatio / 10)).toFixed(0)}px`;
        }
        if (basePaddingBottom) {
            headerCell.style.paddingBottom = `${parseFloat(basePaddingBottom * scaleRatio - (scaleRatio / 10)).toFixed(0)}px`;
        }

        console.log(`Scaling header cell ${index} font-size to: ${headerCell.style.fontSize}, paddingTop to: ${headerCell.style.paddingTop}, paddingBottom to: ${headerCell.style.paddingBottom}`);
    });

    // Scale row font-size, padding, and border width
    const rowCells = table.querySelectorAll("td");
    rowCells.forEach((rowCell, index) => {
        const computedStyles = getComputedStyle(rowCell);
        const baseFontSize = parseFloat(computedStyles.fontSize);
        const basePaddingTop = parseFloat(computedStyles.paddingTop);
        const basePaddingBottom = parseFloat(computedStyles.paddingBottom);

        if (baseFontSize) {
            rowCell.style.fontSize = `${parseFloat(baseFontSize * scaleRatio - (scaleRatio / 10)).toFixed(0)}px`;
        }
        if (basePaddingTop) {
            rowCell.style.paddingTop = `${parseFloat(basePaddingTop * scaleRatio - (scaleRatio / 10)).toFixed(0)}px`;
        }
        if (basePaddingBottom) {
            rowCell.style.paddingBottom = `${parseFloat(basePaddingBottom * scaleRatio - (scaleRatio / 10)).toFixed(0)}px`;
        }

        console.log(`Scaling row cell ${index} font-size to: ${rowCell.style.fontSize}, paddingTop to: ${rowCell.style.paddingTop}, paddingBottom to: ${rowCell.style.paddingBottom}, borderWidth to: ${rowCell.style.borderWidth}`);
    });
}
